### ISSUE TITLE
Way to get around first import error?

### ISSUE THREAD

**Issue by rjakobsson** [meteoric/ionic-sass#2]
When building this on my server, the build fails because of the import error. I'm feeling a bit short on ideas here, anyone else got any?

**Comment by nickw** [comment]
A couple things I can think of:
1. Try a different [SASS package](https://atmospherejs.com/?q=sass) (this requires me to fix meteoric/ionic-sass#1)
2. Clone the repo into your local `packages` directory and see if that helps

**Comment by rjakobsson** [comment]
Thanks Nick, I'll try that!

**Comment by northcoders-chris** [comment]
Any luck @rjakobsson as the compiling for heroku fails and not just a simple reset!

remote:        Errors prevented bundling:
remote:        While building the application:
remote:        client/sass_files/app.scss: Scss compiler error: undefined
remote:        /tmp/build_609cc92177a998e22866c85f34d36ee5/client/sass_files/app.scss:3: file
remote:        to import not found or unreadable:
remote:        '../../.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/ionic'
remote:        Current dir: /tmp/build_609cc92177a998e22866c85f34d36ee5/client/sass_files/

**Comment by rjakobsson** [comment]
@chrishill627 I ended up putting all of the ionic .scss files directly in my sass folder and imported them using

```
@import 'ionic';
@import 'ionicons';
```

That works :) .
