### ISSUE TITLE
Assign Sass variable to dynamic variable

### ISSUE THREAD

**Issue by ghost** [meteoric/ionic-sass#3]
Hi all,

I want to ask if there is a way to change sass variable on the fly, without having to assign it to a fixed value before runtime. Instead of:

<pre>
<code>
// Change Ionic's `positive` color to Meteor's red color:
$positive: #DE4F4F;
</code>
</pre>

Can we do something like:

<pre>
<code>
$positive: {{color}};
</code>
</pre>

with {{color}} being read from meteor collection.

If anyone has done this before, I appreciate the help!! Thanks in advance!

**Comment by nickw** [comment]
Unfortunately, no, as far as I know Meteor doesn't make that possible.
