### ISSUE TITLE
Create multiple theme for multi-tenant app

### ISSUE THREAD

**Issue by ghost** [meteoric/ionic-sass#4]
Hi all,

I am building a multi-tenant app, one of the requirements is different tenant will have different color scheme (including bar, icon, navigation style, ..). I can do this in a limited way by assigning each tenant a theme (like tenant A using bar-positive, tenant B using bar-energized and so on). That's very limited but better than assigning $positive to one color for all the tenants. I want to ask if anyone has a better idea to implement this?

Another requirement is the ability to change color of navbar to any color on the fly - which we will build a front end with some colorpicker for tenant to customize the UI.

I have been searching but haven't found the solution for this. Is there anyway to change ionic color scheme on the fly? 

Thank you so much!

**Comment by nickw** [comment]
You'll probably just have to output a CSS template that contains all the overrides:

```
<template name="themeCSS">
.bar-positive {
  background: #{{tenant.themeColor}};
}
.button-positive {
  background: #{{tenant.themeColor}};
}
// etc, etc
</template>
```
