### ISSUE TITLE
popover backgrounds and styling

### ISSUE THREAD

**Issue by richpowell** [meteoric/ionic-sass#6]
I have two links in my popover. 
.popover is a bit big, and has a bunch of white space below these other links. 
Is there a proper css method you could recommend to adjust to the links heights? Im trying to get ride of all this extra white space. I tried hard coding to height: 80px. but it doesnt look like its adjusting..

**Comment by nickw** [comment]
Yeah I had the same issue, here's what I had to do in the demo app: https://github.com/meteoric/demo/blob/master/client/stylesheets/app.scss#L31

**Comment by richpowell** [comment]
thanks that worked perfectly.
Any tips for styling the color of the up arrow on the popover?
I tried
.popover-arrow{
  background-color:#mycolor;
}
that only changes the background of the arrow.
I also tried color property thinking it might be a ionic font.. that
failed..
thanks for the help
