### ISSUE TITLE
popover-arrow

### ISSUE THREAD

**Issue by richpowell** [meteoric/ionic-sass#7]
Hi Nick, 
Im trying to style the popover arrow, I can change the background of the arrow, and a small area around the arrow changes color.  Is that arrow up an ionic-icon? if so how do you change the colors of those? Do you treat those as a font?  I tried color css property in .popover-arrow but no luck.
Thanks for the help.

**Comment by nickw** [comment]
I'm pretty sure it's using :before or :after pseudo elements. You can inspect those in Chrome's web inspector.
